### ISSUE TITLE
Provide path to the test

### ISSUE THREAD

**Issue by Mattemagikern** [python-tap/pytest-tap#28]
Hello, 

Is it possible to get the relative path to the files in the output to the --tap-combined file? 

Currently it only produces the test name while it skips the path to the file the test function is running in. 

I'd like an option to add the path to the test file in which the function is run. as the pytest module provides.

```bash
blocks/test_stuff2.py::stuff[xml_data0] SKIPPED
blocks/test_stuff.py::test_stuff PASSED
```
How the tapfile provides the output:

```bash
# TAP results for stuff
ok 1 - test_stuff
# TAP results for test_stuff2
ok 2 - test_stuff2 # SKIP not implemented
....
```

Suggested behaviour:
```bash
# TAP results for stuff
ok 1 - blocks/test_stuff.py::test_stuff
# TAP results for test_stuff2
ok 2 - blocks/test_stuff2.py::test_stuff2 # SKIP not implemented
....
```

Id be happy to help if you were to consider this option!

**Comment by mblayman** [comment]
I'm totally open to that option. The reality is that I'm not much of a pytest user so I haven't thought much about the output. If this is a change that brings things closer to what pytest users expect, I'm happy to receive a pull request that would change the format.

I could put out a release after that. pytest-tap is a pretty stable library that doesn't change much and this would be a worthwhile update. Thanks for the suggestion!

**Comment by Mattemagikern** [comment]
I'm having a problem finding some modules:
from tap.formatter import format_as_diagnostics
from tap.tracker import Tracker
. 
Would you mind pointing me in the right direction to the files that should be edited? :)
Also, how do I test the plugin? :)

**Comment by mblayman** [comment]
@Mattemagikern thanks for the kick in the pants to get some "contributing" documentation done. 😄  I added https://github.com/python-tap/pytest-tap#contributing to explain how development is done. Please let me know if it's clear enough or missing critical details.

As for the code you referenced, that stuff comes from `tappy`, the upstream project that manages the TAP data. You can learn more at http://tappy.readthedocs.io/en/latest/. I wrote tappy to work with py.test, nose, and `unittest` so it's the place where all the shared logic happens.

For your purposes, I think the core thing to update is the `description` parameter that goes into `add_ok`, `add_not_ok`, and `add_skip` that is called in `pytest_runtest_logreport`.
