### ISSUE TITLE
TAP plan count doesn't match the output

### ISSUE THREAD

**Issue by lazka** [python-tap/pytest-tap#56]
I have a test suite which looks roughly like

```
1..1234
ok 1 foo
...
ok 900 bar
```

The first line references a larger amount of tests than are actually in the output, which my TAP consumer doesn't like and treats as an error. I haven't looked into creating something reproducible yet, but I thought I'd file it anyway for now.

**Comment by mblayman** [comment]
Can you share the total that your normal pytest run would show? The plugin sets the plan based on how many tests pytest discovers during collection.

https://github.com/python-tap/pytest-tap/blob/master/src/pytest_tap/plugin.py#L79

**Comment by lazka** [comment]
uh, now I can no longer reproduce.. and it matches exactly. Sorry for the noise :/

**Comment by mblayman** [comment]
No problem! I don't have a use case for pytest-tap currently so I'm not keeping up with pytest versions, and I really appreciate your actual user feedback.
