### ISSUE TITLE
Developer docs link is confusing

### ISSUE THREAD

**Issue by jaraco** [python-tap/pytest-tap#72]
I stumbled on pytest-tap through PyPI and I wanted to get started trying it out. I went to https://pypi.org/project/pytest-tap, but it didn't provide any guidance on how to use it. I'd installed it into my test suite, but nothing happened. I tried passing `--tap` (following the convention of so many other pytest plugins that required `--{name}` to be passed to enable the `pytest-{name}` plugin. So I followed the "Developer  documentation" link, but that went to the tappy documentation, which didn't provide any guidance on how to use it. I was eventually able to find the README which provided the necessary command line parameter, `--tap-stream`.

I propose that the long_description should contain the README or at least link to it as the primary documentation and not present tappy docs as their own.

**Comment by mblayman** [comment]
Thanks for the report! That addition makes sense to me. I'd happily accept a PR that updates the long description to refer to the README.
